/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StoreInfo = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getStoreInfo' : IDL.Func([], [StoreInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StoreInfo = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  
  return IDL.Service({ 'getStoreInfo' : IDL.Func([], [StoreInfo], ['query']) });
};

export const init = ({ IDL }) => { return []; };